/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardServicosRouteImport } from './routes/dashboard.servicos'
import { Route as DashboardResultadosRouteImport } from './routes/dashboard.resultados'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardDepoimentosRouteImport } from './routes/dashboard.depoimentos'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as ApiBootstrapAdminRouteImport } from './routes/api.bootstrap-admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicosRoute = DashboardServicosRouteImport.update({
  id: '/dashboard/servicos',
  path: '/dashboard/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResultadosRoute = DashboardResultadosRouteImport.update({
  id: '/dashboard/resultados',
  path: '/dashboard/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/dashboard/leads',
  path: '/dashboard/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDepoimentosRoute = DashboardDepoimentosRouteImport.update({
  id: '/dashboard/depoimentos',
  path: '/dashboard/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/dashboard/configuracoes',
  path: '/dashboard/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapAdminRoute = ApiBootstrapAdminRouteImport.update({
  id: '/api/bootstrap-admin',
  path: '/api/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/depoimentos': typeof DashboardDepoimentosRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/resultados': typeof DashboardResultadosRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/depoimentos': typeof DashboardDepoimentosRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/resultados': typeof DashboardResultadosRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/bootstrap-admin': typeof ApiBootstrapAdminRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/depoimentos': typeof DashboardDepoimentosRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/resultados': typeof DashboardResultadosRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/bootstrap-admin'
    | '/dashboard/configuracoes'
    | '/dashboard/depoimentos'
    | '/dashboard/leads'
    | '/dashboard/resultados'
    | '/dashboard/servicos'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/bootstrap-admin'
    | '/dashboard/configuracoes'
    | '/dashboard/depoimentos'
    | '/dashboard/leads'
    | '/dashboard/resultados'
    | '/dashboard/servicos'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/bootstrap-admin'
    | '/dashboard/configuracoes'
    | '/dashboard/depoimentos'
    | '/dashboard/leads'
    | '/dashboard/resultados'
    | '/dashboard/servicos'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiBootstrapAdminRoute: typeof ApiBootstrapAdminRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardDepoimentosRoute: typeof DashboardDepoimentosRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardResultadosRoute: typeof DashboardResultadosRoute
  DashboardServicosRoute: typeof DashboardServicosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servicos': {
      id: '/dashboard/servicos'
      path: '/dashboard/servicos'
      fullPath: '/dashboard/servicos'
      preLoaderRoute: typeof DashboardServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resultados': {
      id: '/dashboard/resultados'
      path: '/dashboard/resultados'
      fullPath: '/dashboard/resultados'
      preLoaderRoute: typeof DashboardResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/dashboard/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/depoimentos': {
      id: '/dashboard/depoimentos'
      path: '/dashboard/depoimentos'
      fullPath: '/dashboard/depoimentos'
      preLoaderRoute: typeof DashboardDepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/dashboard/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap-admin': {
      id: '/api/bootstrap-admin'
      path: '/api/bootstrap-admin'
      fullPath: '/api/bootstrap-admin'
      preLoaderRoute: typeof ApiBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiBootstrapAdminRoute: ApiBootstrapAdminRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardDepoimentosRoute: DashboardDepoimentosRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardResultadosRoute: DashboardResultadosRoute,
  DashboardServicosRoute: DashboardServicosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
